## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [3]:
# Compilando os dados em um único DataFrame.

df_dados_notas = pd.DataFrame({'acertos_mat': df_mat['Qt_acertos'],
                           'acertos_por': df_por['Qt_acertos'],
                           'acertos_geo': df_geo['Qt_acertos'],
                           'acertos_ing': df_ing['Qt_acertos'],
                           'acertos_his': df_his['Qt_acertos'],
                           'acertos_fis': df_fis['Qt_acertos'],
                           'acertos_qui': df_qui['Qt_acertos']})
df_dados_notas.head()

,acertos_mat,acertos_por,acertos_geo,acertos_ing,acertos_his,acertos_fis,acertos_qui
0,6,7,7,3,1,8,3
1,19,10,0,0,0,11,8
2,14,16,0,5,7,4,4
3,10,7,3,4,0,0,8
4,7,2,2,7,0,9,3

In [4]:
# 1) Calculo do percentual de acerto dos alunos por assunto e adicionar os valores no DataFrame original.

df_dados_notas.insert(1, 'porcentagem_mat', df_dados_notas['acertos_mat']/24)
df_dados_notas.insert(3, 'porcentagem_por', df_dados_notas['acertos_por']/18)
df_dados_notas.insert(5, 'porcentagem_geo', df_dados_notas['acertos_geo']/8)
df_dados_notas.insert(7, 'porcentagem_ing', df_dados_notas['acertos_ing']/8)
df_dados_notas.insert(9, 'porcentagem_his', df_dados_notas['acertos_his']/8)
df_dados_notas.insert(11, 'porcentagem_fis', df_dados_notas['acertos_fis']/12)
df_dados_notas.insert(13, 'porcentagem_qui', df_dados_notas['acertos_qui']/12)

df_dados_notas.head()

,acertos_mat,porcentagem_mat,acertos_por,porcentagem_por,acertos_geo,porcentagem_geo,acertos_ing,porcentagem_ing,acertos_his,porcentagem_his,acertos_fis,porcentagem_fis,acertos_qui,porcentagem_qui
0,6,0.250000,7,0.388889,7,0.875,3,0.375,1,0.125,8,0.666667,3,0.250000
1,19,0.791667,10,0.555556,0,0.000,0,0.000,0,0.000,11,0.916667,8,0.666667
2,14,0.583333,16,0.888889,0,0.000,5,0.625,7,0.875,4,0.333333,4,0.333333
3,10,0.416667,7,0.388889,3,0.375,4,0.500,0,0.000,0,0.000000,8,0.666667
4,7,0.291667,2,0.111111,2,0.250,7,0.875,0,0.000,9,0.750000,3,0.250000

In [5]:
# 2) Calculo do total de acertos de cada aluno e inserindo o valor na última coluna do Dataframe.

df_dados_notas['total_acertos'] = (df_dados_notas['acertos_mat'] +
                                  df_dados_notas['acertos_por'] +
                                  df_dados_notas['acertos_geo'] +
                                  df_dados_notas['acertos_ing'] +
                                  df_dados_notas['acertos_his'] +
                                  df_dados_notas['acertos_fis'] +
                                  df_dados_notas['acertos_qui'])

df_dados_notas['total_acertos']

0     35
1     48
2     50
3     32
4     30
      ..
95    34
96    27
97    40
98    40
99    42
Name: total_acertos, Length: 100, dtype: int64

In [6]:
# 3) Calculo do porcentual geral de cada aluno e inserção deste na última coluna.
# Temos um total de 90 questões

df_dados_notas['porcentagem_total_acertos'] = (df_dados_notas['total_acertos'] / 90)

df_dados_notas['porcentagem_total_acertos']

0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
        ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667
Name: porcentagem_total_acertos, Length: 100, dtype: float64

In [10]:
# 4) Calculo de quantos alunos tiveram nota maior que 45.
# Notas válidas são notas acima de 45 (nota válida > 45)

df_dados_notas['aprovados'] = 0

df_dados_notas.loc[df_dados_notas['total_acertos'] > 45, 'aprovados'] = 1

df_dados_notas['aprovados'].value_counts()

0    69
1    31
Name: aprovados, dtype: int64

In [11]:
# 4) Continuação

qtd_aprovados = df_dados_notas['aprovados'].sum()
print(f'A quantidade de aprovados é: {qtd_aprovados}.')

A quantidade de aprovados é: 31.

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [12]:
# 1) Identificando alunos desclassificados

df_dados_notas['desclassificados'] = 0

df_dados_notas.loc[(df_dados_notas['acertos_mat'] == 0) | (df_dados_notas['acertos_fis'] == 0) | (df_dados_notas['acertos_qui'] == 0), 'desclassificados'] = 1
df_dados_notas['desclassificados']

0     0
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    0
98    1
99    0
Name: desclassificados, Length: 100, dtype: int64

In [13]:
# 1) Criando um novo DataFrame apenas para os desclassificados
df_dados_notas_desc = df_dados_notas[df_dados_notas['desclassificados'] == 1]
df_dados_notas_desc

,acertos_mat,porcentagem_mat,acertos_por,porcentagem_por,acertos_geo,porcentagem_geo,acertos_ing,porcentagem_ing,acertos_his,porcentagem_his,acertos_fis,porcentagem_fis,acertos_qui,porcentagem_qui,total_acertos,porcentagem_total_acertos,aprovados,desclassificados
3,10,0.416667,7,0.388889,3,0.375,4,0.500,0,0.000,0,0.000000,8,0.666667,32,0.355556,0,1
6,6,0.250000,0,0.000000,7,0.875,7,0.875,5,0.625,0,0.000000,4,0.333333,29,0.322222,0,1
10,10,0.416667,8,0.444444,3,0.375,2,0.250,1,0.125,7,0.583333,0,0.000000,31,0.344444,0,1
12,20,0.833333,8,0.444444,3,0.375,7,0.875,1,0.125,0,0.000000,3,0.250000,42,0.466667,0,1
14,7,0.291667,11,0.611111,1,0.125,7,0.875,1,0.125,4,0.333333,0,0.000000,31,0.344444,0,1
20,23,0.958333,11,0.611111,6,0.750,5,0.625,6,0.750,2,0.166667,0,0.000000,53,0.588889,1,1
25,0,0.000000,4,0.222222,7,0.875,4,0.500,0,0.000,4,0.333333,8,0.666667,27,0.300000,0,1
26,11,0.458333,14,0.777778,6,0.750,2,0.250,7,0.875,0,0.000000,0,0.000000,40,0.444444,0,1
27,21,0.875000,13,0.722222,1,0.125,5,0.625,7,0.875,3,0.250000,0,0.000000,50,0.555556,1,1
33,14,0.583333,8,0.444444,0,0.000,5,0.625,6,0.750,6,0.500000,0,0.000000,39,0.433333,0,1
35,11,0.458333,14,0.777778,6,0.750,3,0.375,3,0.375,0,0.000000,11,0.916667,48,0.533333,1,1
49,8,0.333333,1,0.055556,1,0.125,0,0.000,1,0.125,0,0.000000,8,0.666667,19,0.211111,0,1
56,7,0.291667,6,0.333333,7,0.875,5,0.625,6,0.750,0,0.000000,8,0.666667,39,0.433333,0,1
65,1,0.041667,8,0.444444,2,0.250,4,0.500,3,0.375,0,0.000000,6,0.500000,24,0.266667,0,1
66,5,0.208333,4,0.222222,3,0.375,6,0.750,3,0.375,0,0.000000,10,0.833333,31,0.344444,0,1
72,11,0.458333,16,0.888889,3,0.375,4,0.500,7,0.875,0,0.000000,9,0.750000,50,0.555556,1,1
73,1,0.041667,16,0.888889,2,0.250,4,0.500,3,0.375,0,0.000000,11,0.916667,37,0.411111,0,1
74,9,0.375000,11,0.611111,0,0.000,7,0.875,5,0.625,7,0.583333,0,0.000000,39,0.433333,0,1
84,15,0.625000,1,0.055556,0,0.000,5,0.625,1,0.125,0,0.000000,4,0.333333,26,0.288889,0,1
89,23,0.958333,11,0.611111,7,0.875,7,0.875,6,0.750,9,0.750000,0,0.000000,63,0.700000,1,1
92,14,0.583333,10,0.555556,1,0.125,6,0.750,1,0.125,8,0.666667,0,0.000000,40,0.444444,0,1
94,0,0.000000,5,0.277778,2,0.250,6,0.750,1,0.125,3,0.250000,8,0.666667,25,0.277778,0,1
98,0,0.000000,10,0.555556,3,0.375,1,0.125,5,0.625,10,0.833333,11,0.916667,40,0.444444,0,1

In [14]:
# 2) Cálculo dos alunos desclassificados

qtd_desclassificados = df_dados_notas['desclassificados'].sum()
print(f'A quantidade de desclassificados é: {qtd_desclassificados}.')

A quantidade de desclassificados é: 23.

In [15]:
# 3) Média, em história e geografia, dos alunos desclassificados alunos.

media_geo_desc = df_dados_notas_desc['acertos_geo'].mean()
print(f'A média de acertos em geografia dos alunos desclassificados é: {media_geo_desc}')
media_his_desc = df_dados_notas_desc['acertos_his'].mean()
print(f'A média de acertos em história dos alunos desclassificados é: {media_his_desc}')

A média de acertos em geografia dos alunos desclassificados é: 3.217391304347826
A média de acertos em história dos alunos desclassificados é: 3.4347826086956523

In [16]:
# 4) Dataframe para os aprovados e não desclassificados

df_aprovados = df_dados_notas[(df_dados_notas['desclassificados'] == 0) & (df_dados_notas['aprovados'] == 1)]
df_aprovados

,acertos_mat,porcentagem_mat,acertos_por,porcentagem_por,acertos_geo,porcentagem_geo,acertos_ing,porcentagem_ing,acertos_his,porcentagem_his,acertos_fis,porcentagem_fis,acertos_qui,porcentagem_qui,total_acertos,porcentagem_total_acertos,aprovados,desclassificados
1,19,0.791667,10,0.555556,0,0.000,0,0.000,0,0.000,11,0.916667,8,0.666667,48,0.533333,1,0
2,14,0.583333,16,0.888889,0,0.000,5,0.625,7,0.875,4,0.333333,4,0.333333,50,0.555556,1,0
5,20,0.833333,2,0.111111,5,0.625,3,0.375,2,0.250,9,0.750000,9,0.750000,50,0.555556,1,0
7,18,0.750000,4,0.222222,4,0.500,7,0.875,7,0.875,1,0.083333,8,0.666667,49,0.544444,1,0
8,22,0.916667,9,0.500000,2,0.250,7,0.875,6,0.750,5,0.416667,7,0.583333,58,0.644444,1,0
17,21,0.875000,15,0.833333,2,0.250,2,0.250,4,0.500,2,0.166667,6,0.500000,52,0.577778,1,0
18,20,0.833333,4,0.222222,3,0.375,5,0.625,3,0.375,11,0.916667,4,0.333333,50,0.555556,1,0
24,20,0.833333,2,0.111111,7,0.875,5,0.625,3,0.375,11,0.916667,2,0.166667,50,0.555556,1,0
31,15,0.625000,13,0.722222,3,0.375,1,0.125,3,0.375,9,0.750000,10,0.833333,54,0.600000,1,0
36,22,0.916667,9,0.500000,6,0.750,6,0.750,1,0.125,4,0.333333,8,0.666667,56,0.622222,1,0
37,19,0.791667,12,0.666667,5,0.625,7,0.875,1,0.125,6,0.500000,2,0.166667,52,0.577778,1,0
39,4,0.166667,16,0.888889,2,0.250,4,0.500,6,0.750,9,0.750000,8,0.666667,49,0.544444,1,0
40,18,0.750000,3,0.166667,6,0.750,3,0.375,6,0.750,5,0.416667,6,0.500000,47,0.522222,1,0
42,20,0.833333,6,0.333333,7,0.875,7,0.875,2,0.250,3,0.250000,3,0.250000,48,0.533333,1,0
45,17,0.708333,10,0.555556,0,0.000,2,0.250,6,0.750,9,0.750000,4,0.333333,48,0.533333,1,0
48,17,0.708333,6,0.333333,0,0.000,7,0.875,5,0.625,9,0.750000,11,0.916667,55,0.611111,1,0
60,16,0.666667,8,0.444444,0,0.000,4,0.500,4,0.500,7,0.583333,9,0.750000,48,0.533333,1,0
62,17,0.708333,6,0.333333,2,0.250,4,0.500,7,0.875,1,0.083333,9,0.750000,46,0.511111,1,0
67,21,0.875000,0,0.000000,7,0.875,2,0.250,4,0.500,2,0.166667,10,0.833333,46,0.511111,1,0
70,21,0.875000,14,0.777778,0,0.000,3,0.375,5,0.625,11,0.916667,8,0.666667,62,0.688889,1,0
71,17,0.708333,8,0.444444,7,0.875,6,0.750,4,0.500,2,0.166667,9,0.750000,53,0.588889,1,0
77,15,0.625000,2,0.111111,5,0.625,7,0.875,6,0.750,11,0.916667,7,0.583333,53,0.588889,1,0
78,14,0.583333,16,0.888889,7,0.875,2,0.250,7,0.875,11,0.916667,9,0.750000,66,0.733333,1,0
81,22,0.916667,16,0.888889,2,0.250,0,0.000,4,0.500,1,0.083333,10,0.833333,55,0.611111,1,0
88,20,0.833333,1,0.055556,1,0.125,5,0.625,7,0.875,9,0.750000,7,0.583333,50,0.555556,1,0
93,12,0.500000,16,0.888889,5,0.625,5,0.625,6,0.750,6,0.500000,6,0.500000,56,0.622222,1,0

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [49]:
# arquivo = 'https://s3-sa-east-1.amazonaws.com/ckan.saude.gov.br/PNI/vacina/uf/2021-05-23/uf%3DAC/part-00000-63e5bee2-3684-4286-b709-7fe85483b04e.c000.csv'

In [17]:
# 1)

df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')

In [18]:
df.head()

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN

In [19]:
df.shape[0]

169071

In [20]:
# 2) 
df['paciente_id'].nunique()

120517

In [21]:
# 3) 
primeira_dose = df['vacina_descricao_dose'].unique()[0]
df['paciente_id'].loc[df['vacina_descricao_dose'] == primeira_dose].nunique()

119713

In [23]:
# 4) 
df_menor = df[df["paciente_idade"]<18]
df_menor['paciente_id'].nunique()

47

In [24]:
# 5)
df['estabelecimento_razaosocial'].nunique()

42

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vcinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [25]:
# 1) 

df_menor = df[df["paciente_idade"]<18].copy()

In [26]:
# 2) 

df_menor.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [27]:
# 3)

df_menor['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [28]:
# 4)

lista_variaveis = ['estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']

In [29]:
# 5)

df_menor_lista = df_menor.loc[:,lista_variaveis]

In [30]:
# 6)
df_menor_lista = df_menor_lista.drop_duplicates()
df_menor_lista.shape

(18, 6)

In [31]:
df_menor_lista

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC
17153,6748759,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE FEIJO,120030,FEIJO,AC
18361,6308740,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE PORTO WALTER,120039,PORTO WALTER,AC
18608,2001748,PREFEITURA MUNICIPAL DE PORTO WALTER,UBS VICENTE VARELA DE ALMEIDA,120039,PORTO WALTER,AC
20204,6917682,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
21119,6428940,PREFEITURA MUNICIPAL DE ASSIS BRASIL,POLO BASE DE ASSIS BRASIL,120005,ASSIS BRASIL,AC
29127,6612385,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...,120060,TARAUACA,AC
57405,9648968,DISTRITO SANITARIO ESPECIAL DE SAUDE INDIGENA ...,POLO INDIGENA DE MANOEL URBANO,120034,MANOEL URBANO,AC
61131,6430201,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO JURUA,POLO BASE INDIGENA,120032,JORDAO,AC
68290,6955525,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MANCIO LIMA,120033,MANCIO LIMA,AC
69882,5336171,SECRETARIA DE ESTADO DE SAUDE DO ACRE,HOSPITAL REGIONAL DO JURUA,120020,CRUZEIRO DO SUL,AC
70881,6697151,MINISTERIO DA SAUDE,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS,120050,SENA MADUREIRA,AC
101402,3323307,PREFEITURA MUNICIPAL DE PORTO ACRE,UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE,120080,PORTO ACRE,AC
140895,7123043,PREFEITURA MUNICIPAL DE JORDAO,SAUDE DA FAMILIA RIBEIRINHA,120032,JORDAO,AC